# Generated by Django 2.2.7 on 2019-11-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_auto_20191107_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='prise',
            new_name='price',
        ),
    ]
