# Generated by Django 2.2.7 on 2019-11-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='ae3b8a7c00ed4403a9512b6ee93eb6eea4e2743ea21b47eaa70c25a3af09b7fa', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='ea487b5066084b82915baca2a1abfac9f6680723d9cc4c88ab96a1bcb3c5ed80', max_length=300, null=True),
        ),
    ]
