# Generated by Django 2.2.7 on 2019-11-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191113_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='525ee04666f04c5281cd4335afbd07b807e212881fad47eba961712f181033a8', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='ab91c3227f734426aafaf8fce58d5baa038c2a80a1cf4e2badbb09950658fa60', max_length=300, null=True),
        ),
    ]
