# Generated by Django 2.2.7 on 2019-11-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191113_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='82ce5dc7360f435f8322afcbcd3b012371810669fedc43bf9e0e4e01b1cf72e7', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='063ca544f27b42d6a94ada510e0e918bdc393474677047bbbc157490fa1cb7b6', max_length=300, null=True),
        ),
    ]
