# Generated by Django 2.2.7 on 2019-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191114_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='61dca8c998de4614a62baa446e1776ae21f073d6f19e46809cd41ee05c430a01', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='0f8c5472d9d24ef8b8c9e36397321a230ab2e512dc184e7586522511e18b62dc', max_length=300, null=True),
        ),
    ]
