# Generated by Django 2.2.7 on 2019-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191114_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='739a8a6b9310459fbad3f9980eaed7092c0e884441c84ae8a9a0fc1022e6d41b', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='d507216d9982488e8b8805f6d9eb1cb8d25240d90e554542af7b1c5e97848d9b', max_length=300, null=True),
        ),
    ]
