# Generated by Django 2.2.7 on 2019-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191114_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='c7faa5f63db9498a9925e3350ca2336c51f831846c6349589d180840866f2530', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='4fdbfa65f93f4fb3b0eda510fe497832542c25fd965e4c70bd3332bdc8d750c3', max_length=300, null=True),
        ),
    ]
